### ISSUE TITLE
HeaderStamp modifies files in vendor/ folder

### ISSUE THREAD

**Issue by matks** [PrestaShopCorp/header-stamp#12]
1) clone prestashop/welcome module
2) `$ composer require --dev prestashop/php-dev-tools$ 
3) Look at file `vendor/Symfony/console/Tests/Fixtures/FooSameCaseUppercaseCommand.php` its header have been modified to use the ones for PrestaShop

**Comment by matks** [comment]
Other files are modified in vendor/ folder too. But not all of them.

**Comment by Matt75** [comment]
https://github.com/PrestaShopCorp/header-stamp/blob/f985505bb8352b457ee0b67262d79b9bb1beb456/src/Command/UpdateLicensesCommand.php#L97

**Comment by Quetzacoalt91** [comment]
At the moment the folders to exclude have to be specified (this also applies to the `node_modules/` folder).

I didn't know how the command should behave when you specify this param (do you replace or add to the list?), so I decided to keep the list empty by default.

**Comment by matks** [comment]
This can be improved by https://github.com/matks/header-stamp/pull/1

**Comment by matks** [comment]
Fixed
